thesisproject/predict/urls.py
from django.urls import path
from . import views

app_name = "predict"

urlpatterns = [
    path('', views.predict, name='prediction_page'),
    path('predict/', views.predict_chances, name='submit_prediction'),
    path('results/', views.view_results, name='results'),
]

thesisproject/thesisproject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('predict.urls', namespace='predict'))
]

thesisproject/predict/models.py
from django.db import models

# Create your models here.
class PredResults(models.Model):

    floor_num = models.FloatField()
    floor_area = models.FloatField()
    column_area = models.FloatField()
    concrete_wall_areaNS = models.FloatField()
    concrete_wall_areaEW = models.FloatField()
    masonry_wall_areaNS = models.FloatField()
    masonry_wall_areaEW = models.FloatField()
    captive_column = models.BooleanField()
    classification = models.CharField(max_length=30)

    def __str__(self):
        return self.classification

thesisproject/predict/views.py
from django.shortcuts import render
from django.http import JsonResponse
import pandas as pd
from .models import PredResults


def predict(request):
    return render(request, 'predict.html')


def predict_chances(request):

    if request.POST.get('action') == 'post':

        # Receive data from client
        floor_num = float(request.POST.get('floor_num'))
        floor_area = float(request.POST.get('floor_area'))
        column_area = float(request.POST.get('column_area'))
        concrete_wall_areaNS = float(request.POST.get('concrete_wall_areaNS'))
        concrete_wall_areaEW = float(request.POST.get('concrete_wall_areaEW'))
        masonry_wall_areaNS = float(request.POST.get('masonry_wall_areaNS'))
        masonry_wall_areaEW = float(request.POST.get('masonry_wall_areaEW'))
        captive_column = float(request.POST.get('captive_column'))

        # Unpickle model
        model = pd.read_pickle(r".new_randomforest.pickle")
        # Make prediction
        result = model.predict([[floor_num, floor_area, column_area, concrete_wall_areaNS, 
        concrete_wall_areaEW, masonry_wall_areaNS, masonry_wall_areaEW, captive_column]])

        classification = result[0]

        PredResults.objects.create(floor_num=floor_num, floor_area=floor_area, column_area=column_area,
                                   concrete_wall_areaNS=concrete_wall_areaNS, concrete_wall_areaEW=concrete_wall_areaEW, 
                                   masonry_wall_areaNS=masonry_wall_areaNS, masonry_wall_areaEW=masonry_wall_areaEW, 
                                   captive_column=captive_column, classification=classification)

        return JsonResponse({'result': classification, 'floor_num': floor_num, 'floor_area': floor_area,
                             'column_area': column_area, 'concrete_wall_areaNS': concrete_wall_areaNS, 
                             'concrete_wall_areaEW': concrete_wall_areaEW,'masonry_wall_areaNS': masonry_wall_areaNS,
                             'masonry_wall_areaEW': masonry_wall_areaEW, 'captive_column': captive_column},
                            safe=False)


def view_results(request):
    # Submit prediction and show all
    data = {"dataset": PredResults.objects.all()}
    return render(request, "results.html", data)

thesisproject/templates/base.html
<!doctype html>
<html lang="en">
    <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <title>Seismic Damage Prediction</title>
    </head>
    <body>


    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="/">Seismic Damage Prediction <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/results">DB</a>
                </li>
            </ul>
        </div>
    </nav>

    {% block main %}
    {% endblock %}

    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    </body>
</html>

thesisproject/templates/predict.html
{% extends "base.html" %}

{% block main %}
<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Prediction Results</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <h5>Prediction Input:</h5>
                <div>Floor Number: <span id="fn"></span></div>
                <div>Total Floor Area: <span id="fa"></span></div>
                <div>Column Area: <span id="ca"></span></div>
                <div>Concrete Wall AreaNS: <span id="cwns"></span></div>
                <div>Concrete Wall AreaEW: <span id="cwew"></span></div>
                <div>Masonry Wall AreaNS: <span id="mwns"></span></div>
                <div>Masonry Wall AreaEW: <span id="mwew"></span></div>
                <div>Captive Column: <span id="cc"></span></div>
                <h5 class="pt-3">Prediction Classification:</h5>
                <div id="prediction"></div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <a class="btn btn-primary" href="/results" role="button">View DB</a>
            </div>
        </div>
    </div>
</div>

<div class="container pt-5">
    <div class="row justify-content-md-center">
        <div class="col-md-4">
            <h1>Seismic Damage Prediction</h1>
            <form action="" id="post-form">
                {% csrf_token %}
                <div class="form-group">
                    <label for="floor_num">Floor Number</label>
                    <input type="number" step="1" class="form-control" id="floor_num" placeholder="" required>
                </div>
                <div class="form-group">
                    <label for="floor_area">Total Floor Area</label>
                    <input type="number" step="1" class="form-control" id="floor_area" placeholder="" required>
                </div>
                <div class="form-group">
                    <label for="column_area">Column Area</label>
                    <input type="number" step="0.1" class="form-control" id="column_area" placeholder="" required>
                </div>
                <div class="form-group">
                    <label for="concrete_wall_areaNS">Concrete Wall AreaNS</label>
                    <input type="number" step="0.1" class="form-control" id="concrete_wall_areaNS" placeholder="" required>
                </div>
                <div class="form-group">
                    <label for="concrete_wall_areaEW">Concrete Wall AreaEW</label>
                    <input required type="number" step="0.1" class="form-control" id="concrete_wall_areaEW" placeholder="" required>
                </div>
                <div class="form-group">
                    <label for="masonry_wall_areaNS">Masonry Wall AreaNS</label>
                    <input type="number" step="0.1" class="form-control" id="masonry_wall_areaNS" placeholder="" required>
                </div>
                <div class="form-group">
                    <label for="masonry_wall_areaEW">Masonry Wall AreaEW</label>
                    <input type="number" step="0.1" class="form-control" id="masonry_wall_areaEW" placeholder="" required>
                </div>
                <div class="form-group">
                    <label for="captive_column">Captive Column</label>
                    <input type="boolean" class="form-control" id="captive_column" placeholder="" required>
                </div>
                <button type="submit" value="Submit" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">Submit</button>
            </form>
        </div>
    </div>
</div>

<script>
    $(document).on('submit', '#post-form',function(e){
        e.preventDefault();
        $.ajax({
            type:'POST',
            url:'{% url "predict:submit_prediction" %}',
            data:{
                floor_num:$('#floor_num').val(),
                floor_area:$('#floor_area').val(),
                column_area:$('#column_area').val(),
                concrete_wall_areaNS:$('#concrete_wall_areaNS').val(),
                concrete_wall_areaEW:$('#concrete_wall_areaEW').val(),
                masonry_wall_areaNS:$('#masonry_wall_areaNS').val(),
                masonry_wall_areaEW:$('#masonry_wall_areaEW').val(),
                captive_column:$('#captive_column').val(),
                csrfmiddlewaretoken:$('input[name=csrfmiddlewaretoken]').val(),
                action: 'post'
            },
            success:function(json) {
                document.forms["post-form"].reset();
                document.getElementById("prediction").innerHTML = json['result']
                document.getElementById("fn").innerHTML = json['floor_num']
                document.getElementById("fa").innerHTML = json['floor_area']
                document.getElementById("ca").innerHTML = json['column_area']
                document.getElementById("cwns").innerHTML = json['concrete_wall_areaNS']
                document.getElementById("cwew").innerHTML = json['concrete_wall_areaEW']
                document.getElementById("mwns").innerHTML = json['masonry_wall_areaNS']
                document.getElementById("mwew").innerHTML = json['masonry_wall_areaEW']
                document.getElementById("cc").innerHTML = json['captive_column']
            },
            error : function(xhr,errmsg,err) {

            }
        });
    })
</script>

{% endblock %}

thesisproject/templates/results.html
{% extends "base.html" %}

{% block main %}
    <div class="container pt-5">
        <div class="row">

        <h1>Prediction Results</h1>

            <table class="table">
                <thead>
                <tr>
                <th scope="col">#</th>
                <th scope="col">Floor Number</th>
                <th scope="col">Total Floor Area</th>
                <th scope="col">Column Area</th>
                <th scope="col">Concrete Wall AreaNS</th>
                <th scope="col">Concrete Wall AreaEW</th>
                <th scope="col">Masonry Wall AreaNS</th>
                <th scope="col">Masonry Wall AreaEW</th>
                <th scope="col">Captive Column</th>
                <th scope="col">Prediction</th>
                </tr>
                </thead>
                <tbody>
                {% for data in dataset %}
                    <tr>
                    <th scope="row">{{ data.id }}</th>
                    <td>{{ data.floor_num }}</td>
                    <td>{{ data.floor_area }}</td>
                    <td>{{ data.column_area }}</td>
                    <td>{{ data.concrete_wall_areaNS }}</td>
                    <td>{{ data.concrete_wall_areaEW }}</td>
                    <td>{{ data.masonry_wall_areaNS }}</td>
                    <td>{{ data.masonry_wall_areaEW }}</td>
                    <td>{{ data.captive_column }}</td>
                    <td>{{ data.classification }}</td>
                    </tr>
                {% endfor %}

                </tbody>
            </table>
        </div>
    </div>
{% endblock %}